### ISSUE TITLE
Graph not working

### ISSUE THREAD

**Issue by muguirapp** [agrignard/UrbanSwarms#13]
In Tangible Intersection, I created a road graph representing an intersection in QGIS. When I transferred it to GAMA, and command my toio agent to move along the graph, it is not able to go from an edge to a different edge. I suppose it is because GAMA is not reading the graph as those edges being connected by a vertex. How can we fix that issue? Either in GAMA or in QGIS.

**Comment by muguirapp** [comment]
@agrignard the .shp file is the only one inside the includes folder of the Tangible Intersection project. I don't know where the issue could be on the code since the code is not giving me any bugs and I have created the graph mirroring how the library models create theirs.

**Comment by agrignard** [comment]
Excuse me I just sse this issue now. I assume it is out of date?
